apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: celldstacks.hops.ops.com.ai
spec:
  compositeTypeRef:
    apiVersion: hops.ops.com.ai/v1alpha1
    kind: CelldStack
  mode: Pipeline
  pipeline:
  - functionRef:
      name: hops-ops-celld-stackrender
    step: render
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
